export default {
  clearMocks: true,
  coverageDirectory: "coverage",
  coverageReporters: ["text-summary", "lcov"],
  coverageProvider: "v8",
  preset: "ts-jest",
  testEnvironment: "node",
  testMatch: ["**.spec.ts"],
  watchPathIgnorePatterns: ["node_modules"],
  moduleNameMapper: {
    "^@config/(.*)$": "<rootDir>/src/config/$1",
    "^@controllers/(.*)$": "<rootDir>/src/controllers/$1",
    "^@core/(.*)$": "<rootDir>/src/core/$1",
    "^@entities/(.*)$": "<rootDir>/src/entities/$1",
    "^@infra/(.*)$": "<rootDir>/src/infra/$1",
    "^@main/(.*)$": "<rootDir>/src/main/$1",
    "^@presenters/(.*)$": "<rootDir>/src/presenters/$1",
    "^@repositories/(.*)$": "<rootDir>/src/repositories/$1",
    "^@shared/(.*)$": "<rootDir>/src/shared/$1",
    "^@useCases/(.*)$": "<rootDir>/src/useCases/$1",
    "^@tests/(.*)$": "<rootDir>/tests/$1",
  },
};
